GPT_4_MODEL = 'gpt-4'
GET_KEY_TIMEOUT = 30  # 30 seconds
SAVE_RESULT_GET_KEY_TIMEOUT = 60 * 15  # 15 minutes
UPDATE_STATUS_KEY_TYPE_RELEASE = 'release'
UPDATE_STATUS_KEY_TYPE_DISABLE = 'disable'
UPDATE_STATUS_KEY_TYPE_ENABLE = 'enable'
UPDATE_STATUS_KEY_TYPE_INCREASE = 'increase'
